services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres:postgres
    ports:
      - '8080:80'
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres:
    driver: local
  pg-admin:
    driver: local

networks:
  postgres:
    driver: bridge
